app:
  music:
    storage:
      path: D:/microservice_musics

server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: song-streaming-microservice
  config:
    import: optional:configserver:http://{CONFIG_SERVER_USERNAME:config}:{CONFIG_SERVER_PASSWORD:config}@configserver:8080
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/song_path
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      password: dir
      name: dir




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true